export const Routes = {
  home: "/",
  login: "/auth/login",
  categories: "/categories",
  register: "/auth/register",
  clientRegister: "/auth/register/client",
  providerRegister: "/auth/register/provider",
  singleCategory: (slug: string) => `/categories/${slug}`,
  singleService: (id: string) => `/service/product/${id}`,
  providers: "/providers",
  singleProvider: (username: string) => `/providers/${username}`,
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",
  adminCategories: "/admin/category",
  adminSingleCategory: (slug: string) => `/admin/category/${slug}`,
  adminActivities: "/admin/activity",
  adminDisputes: "/admin/dispute",
  adminCreateCategory: "/admin/category/create",
};
